hpcData = read.table("household_power_consumption.txt",sep=";", col.names=c("Date","Time","GAp","GAr","V","Gi","SM1","SM2","SM3"),fill=FALSE,header=TRUE, na.strings="?")
hpcData$Date<-strptime(as.character(hpcData$Date),"%d/%m/%Y")
hpcData$Date<-format(hpcData$Date,"%Y-%m-%d")
hpcData$Time<-strptime(as.character(hpcData$Time),format="%H:%M:%S")
hpcData$Time<-format(hpcData$Time,"%H:%M:%S")
hpcDataFeb<-subset(hpcData, Date =="2007-02-01" | Date == "2007-02-02" | (Date == "2007-02-03" & Time == "00:00:00"))
library(chron)
hpcDataFeb$DateTime=chron(dates=hpcDataFeb[,1],times=hpcDataFeb[,2],format=c('y-m-d','h:m:s'))
hpcDataFeb$DateTime<-as.POSIXlt(hpcDataFeb$DateTime,tz="GMT")
png(filename="plot4.png",width=480,height=480,units="px")
par(mfcol=c(2,2), mar=c(5,5,2,2))
plot(hpcDataFeb$DateTime,hpcDataFeb$GAp, type = "s", xlab="", ylab="Global Active Power")
with(hpcDataFeb,plot(hpcDataFeb$DateTime,hpcDataFeb$SM1,type="n",xlab="",ylab="Energy sub metering"))
with(hpcDataFeb,{
        points(hpcDataFeb$DateTime,hpcDataFeb$SM1, type = "s")
        points(hpcDataFeb$DateTime,hpcDataFeb$SM2, type = "s",col="orangered")
        points(hpcDataFeb$DateTime,hpcDataFeb$SM3, type = "s",col="blue")})
legend("topright", lty=1, bty= "n",col = c("black","orangered","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(hpcDataFeb$DateTime,hpcDataFeb$V, type = "s", xlab="datetime", ylab="Voltage")
plot(hpcDataFeb$DateTime,hpcDataFeb$GAr, type = "s", xlab="datetime", ylab="Global_reactive_power")
dev.off()